# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Health Check Tests + AdminApi

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  JIRA_ACCESS_TOKEN: ${{ secrets.JIRA_ACCESS_TOKEN }}
  ADMIN_API_VERSION: "1.2"
  PROJECT_ID: "13401"
  CYCLE_NAME: "Automation Cycle"
  TASK_NAME: "API Automation Task"
  FOLDER_NAME: "API Automation Run"
  RESULTS_FILE: "test-xml-results"

permissions: read-all

jobs:
  run-health-check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4.1.1
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker
          ref: adminconsole1-rc.0
      - name: Run Admin API
        run: |
          ls

      - name: Run Admin API
        run: |
          docker compose \
          --profile default -f ./Compose/pgsql/SingleTenant/compose-single-tenant-env.yml \
          --env-file ./.env up -d

      - name: Verify containers are running
        run: |
          chmod +x './E2E Tests/gh-action-setup/inspect.sh'
          './E2E Tests/gh-action-setup/inspect.sh' adminapi

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "16"

      - name: Install Tools
        run: npm install -g newman@6.1.3

      - name: Run tests
        run: |
          newman run './E2E Tests/Admin API Setup 2.0 - Admin Console Instances.postman_collection.json' \
            -e './E2E Tests/Admin API Docker-single-pgsql.postman_environment.json' \
            -r cli \
            -k
      - name: Build Admin Console Health Check Service
        run: |
          docker build -f Docker/Dockerfile -t edfi.adminconsole.healthcheckservice .

      - name: Run Docker Health Check
        run: |
          docker run -it edfi.adminconsole.healthcheckservice \
          --ClientId="edfi" --ClientSecret="AzoAn4wrhnyJPGV/vsL4Zvj6AB2zEbmTMHuf37tpdxQ="

      - name: Get Docker logs
        if: failure()
        run: |
          mkdir docker-logs
          docker logs ed-fi-db-admin-adminapi > docker-logs/ed-fi-db-admin-adminapi.log
          docker logs adminapi > docker-logs/adminapi.log

      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: docker-logs
          path: Application/EdFi.Ods.AdminApi/docker-logs/
          retention-days: 5

